# Main Branch Deployment Workflow

name: Main Branch (Tagged Release) Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on pushed tag
  push:
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Job scoped environment variables
    env:
      BUILD_CONFIGURATION: Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set variables
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build
      - name: Build
        run: >
          dotnet build
          --no-restore
          --configuration $env:BUILD_CONFIGURATION
          /p:Version=$env:VERSION
          --nologo
      
      # Test (if present)
      - name: Test
        run: >
          dotnet test
          --no-build
          --configuration $env:BUILD_CONFIGURATION
          --verbosity normal
          --nologo
      
      # Create the preview package
      - name: Pack
        run: >
          dotnet pack
          --no-build
          --configuration $env:BUILD_CONFIGURATION
          --include-symbols
          /p:Version=$env:VERSION
          --output .
      
      # Upload release
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./*.nupkg
